---
# Test Environment Docker Compose Configuration
# Standalone test configuration with ephemeral storage
# Run with: docker compose -f compose.test.yml up
# Or: just test (if using justfile)

name: saga-test

services:
  kafka-test:
    image: apache/kafka:4.1.0
    hostname: kafka-test
    container_name: kafka-test
    ports:
      - "127.0.0.1:9093:9092"
    entrypoint: /opt/kafka/scripts/entrypoint.sh
    environment:
      # KRaft Mode Configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-test:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listener Configuration
      KAFKA_LISTENERS: CONTROLLER://kafka-test:9093,INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-test:29092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Single Node Replication Settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Test Environment Settings
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

    volumes:
      - ./docker/kafka/entrypoint.sh:/opt/kafka/scripts/entrypoint.sh:ro
    # NO persistent volumes - ephemeral Kafka for testing
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 8
      start_period: 20s
    networks:
      - sales-test-network

  sale-service-test:
    build:
      context: ./saga-choreography/sale-service
      dockerfile: Dockerfile
    container_name: sale-service-test
    ports:
      - "127.0.0.1:8091:8081"
    depends_on:
      sale-db-test:
        condition: service_healthy
      kafka-test:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sale-db-test:3306/${SALE_DB_NAME:-sales_db}
      SPRING_DATASOURCE_USERNAME: ${SALE_DB_APP_USERNAME:-sales_app_user}
      SPRING_DATASOURCE_PASSWORD: ${SALE_DB_APP_USER_PWD:-123456}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-test:29092
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --output /dev/null --write-out '%{http_code}' http://localhost:8081/api/v1/sales | grep -qE '^(405|200)$'"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 25s
    networks:
      - sales-test-network

  inventory-service-test:
    build:
      context: ./saga-choreography/inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service-test
    ports:
      - "127.0.0.1:8092:8082"
    depends_on:
      inventory-db-test:
        condition: service_healthy
      kafka-test:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://inventory-db-test:3306/${INVENTORY_DB_NAME:-inventory_db}
      SPRING_DATASOURCE_USERNAME: ${INVENTORY_DB_APP_USERNAME:-inventory_app_user}
      SPRING_DATASOURCE_PASSWORD: ${INVENTORY_DB_APP_USER_PWD:-123456}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-test:29092
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --output /dev/null --write-out '%{http_code}' http://localhost:8082 | grep -qE '^[2-5][0-9][0-9]$'"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 25s
    networks:
      - sales-test-network

  payment-service-test:
    build:
      context: ./saga-choreography/payment-service
      dockerfile: Dockerfile
    container_name: payment-service-test
    ports:
      - "127.0.0.1:8093:8083"
    depends_on:
      payment-db-test:
        condition: service_healthy
      kafka-test:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://payment-db-test:3306/${PAYMENT_DB_NAME:-payment_db}
      SPRING_DATASOURCE_USERNAME: ${PAYMENT_DB_APP_USERNAME:-payment_app_user}
      SPRING_DATASOURCE_PASSWORD: ${PAYMENT_DB_APP_USER_PWD:-123456}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-test:29092
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --output /dev/null --write-out '%{http_code}' http://localhost:8083 | grep -qE '^[2-5][0-9][0-9]$'"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 25s
    networks:
      - sales-test-network

  sale-db-test:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
      args:
        DB_NAME: ${SALE_DB_NAME:-sales_db}
        ROOT_PWD: ${SALE_DB_ROOT_PWD:-root}
        APP_USERNAME: ${SALE_DB_APP_USERNAME:-sales_app_user}
        APP_USER_PWD: ${SALE_DB_APP_USER_PWD:-123456}
    container_name: sale-db-test
    ports:
      - "127.0.0.1:3318:3306"
    environment:
      DB_NAME: ${SALE_DB_NAME:-sales_db}
      ROOT_PWD: ${SALE_DB_ROOT_PWD:-root}
    # NO volumes - ephemeral database for testing
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$ROOT_PWD && mysql -uroot -p$$ROOT_PWD -e 'SELECT 1' $$DB_NAME"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 20s
    networks:
      - sales-test-network

  inventory-db-test:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
      args:
        DB_NAME: ${INVENTORY_DB_NAME:-inventory_db}
        ROOT_PWD: ${INVENTORY_DB_ROOT_PWD:-root}
        APP_USERNAME: ${INVENTORY_DB_APP_USERNAME:-inventory_app_user}
        APP_USER_PWD: ${INVENTORY_DB_APP_USER_PWD:-123456}
    container_name: inventory-db-test
    ports:
      - "127.0.0.1:3319:3306"
    environment:
      DB_NAME: ${INVENTORY_DB_NAME:-inventory_db}
      ROOT_PWD: ${INVENTORY_DB_ROOT_PWD:-root}
    volumes:
      # Only init script, no persistent data (uses test-specific init file)
      - ./docker/database/init-inventory-db.test.sql:/docker-entrypoint-initdb.d/1-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$ROOT_PWD && mysql -uroot -p$$ROOT_PWD -e 'SELECT 1' $$DB_NAME"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 20s
    networks:
      - sales-test-network

  payment-db-test:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
      args:
        DB_NAME: ${PAYMENT_DB_NAME:-payment_db}
        ROOT_PWD: ${PAYMENT_DB_ROOT_PWD:-root}
        APP_USERNAME: ${PAYMENT_DB_APP_USERNAME:-payment_app_user}
        APP_USER_PWD: ${PAYMENT_DB_APP_USER_PWD:-123456}
    container_name: payment-db-test
    ports:
      - "127.0.0.1:3320:3306"
    environment:
      DB_NAME: ${PAYMENT_DB_NAME:-payment_db}
      ROOT_PWD: ${PAYMENT_DB_ROOT_PWD:-root}
    volumes:
      # Only init script, no persistent data (uses test-specific init file)
      - ./docker/database/init-user-db.test.sql:/docker-entrypoint-initdb.d/1-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$ROOT_PWD && mysql -uroot -p$$ROOT_PWD -e 'SELECT 1' $$DB_NAME"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 20s
    networks:
      - sales-test-network

networks:
  sales-test-network:
    driver: bridge

# NO volumes section - all data is ephemeral
